[package]
name    = "rkapi"
version = "0.0.1"
authors = ["Will <will@kentik.com>"]
edition = "2018"

[dependencies]
log               = "0.4.6"
crossbeam-channel = "0.3.8"
serde             = "1.0.89"
serde_derive      = "1.0.89"

[dependencies.reqwest]
version  = "0.9.11"
features = ["rustls-tls"]
default-features = false

[dev-dependencies]
env_logger = "0.6.1"
serde_json = "1.0.39"

[profile.release]
lto   = true
debug = false
